version: "3.8"

networks:
  discorder_network: 

services:

  database:
    image: mysql:latest
    container_name: discorder_database
    environment:
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
    networks:
      - discorder_network

  php-fpm:
    build:
      context: ./
      dockerfile: ./Docker/php-fpm/Dockerfile
    container_name: discorder_php
    links: 
      - database
    volumes: 
      - wp:/var/www/html
    networks:
      - discorder_network

  nginx:
    build:
      context: ./
      dockerfile: ./Docker/nginx/Dockerfile
    container_name: discorder_nginx
    depends_on: 
      - php-fpm
      - database
    ports:
      - 80:80
    volumes: 
      - wp:/var/www/html
    networks:
      - discorder_network

  phpmyadmin:
    depends_on:
      - database
    image: phpmyadmin/phpmyadmin
    container_name: discorder_phpmyadmin
    links:
      - database
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
    restart: always
    ports:
      - 8081:80
    networks:
      - discorder_network

volumes:

  wp:
  db: